[network]
name = "mainnet"
stacks_node_rpc_address = "https://api.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "give genius poverty chat height chair alien travel walk battle youth slight behind lend glad shove famous clutch vessel near index century permit head"
